services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: celsia
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: sgcp
      
      
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    #para codar com o manage 
    #command: python manage.py runserver 0.0.0.0:8000
    comand: gunicorn projectsgcp.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_USER: celsia
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: sgcp
      POSTGRES_HOST: db #porque est√° rodando dentro do docker e acessando pelo get no setting

volumes:
  postgres_data: